package com.hdu.entity.domain;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

public class Bank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.id
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.username
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    @NotBlank
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.money
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    @NotNull
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.id
     *
     * @return the value of bank.id
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.id
     *
     * @param id the value for bank.id
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.username
     *
     * @return the value of bank.username
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.username
     *
     * @param username the value for bank.username
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.money
     *
     * @return the value of bank.money
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.money
     *
     * @param money the value for bank.money
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}