package com.hdu.mapper;

import com.hdu.entity.domain.Bank;
import com.hdu.entity.domain.BankExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @author Administrator
 */
@Mapper
public interface BankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    long countByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int deleteByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int insert(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int insertSelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    List<Bank> selectByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    Bank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") Bank record, @Param("example") BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int updateByExample(@Param("record") Bank record, @Param("example") BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int updateByPrimaryKeySelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated Sat Apr 24 18:13:14 CST 2021
     */
    int updateByPrimaryKey(Bank record);
}